[project]
name = "google-shipping-helpline-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "google-ai-generativelanguage>=0.6.18",
    "langchain>=0.3.24",
    "langchain-community>=0.3.23",
    "langchain-core>=0.3.56",
    "langchain-google-community>=2.0.7",
    "langchain-google-genai>=2.1.4",
    "langchain-openai>=0.3.14",
    "langfuse>=2.60.3",
    "langgraph>=0.4.1",
    "mem0ai>=0.1.95",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
    "websockets>=15.0.1",
]
